name: Prod Workflow
'on':
  push:
    branches:
      - main
jobs:
  frontend_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install Dependencies
        run: cd client && npm i
      - name: deploy
        run: npm run deploy