name: Prod Workflow
'on':
  push:
    branches:
      - main
jobs:
  frontend_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
      - name: deploy
        run: git config --global user.name '${GITHUB_ACTOR}' && git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com' && cd client && npm i && CI=false npm run deploy