name: Prod Workflow
'on':
  push:
    branches:
      - main
jobs:
  frontend_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install Dependencies
        run: npm ci
      - name: deploy
        run: npm run deploy
  # backend_deploy:
  #   needs: prod_build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@v2
  #     - name: Download Dependencies for Cloud Functions

  #       run: cd functions && npm install && cd ..
  #     - name: Download Artifact
  #       uses: actions/download-artifact@master
  #       with:
  #         name: dist
  #         path: dist
  #     - uses: w9jds/firebase-action@master
  #       with:
  #         args: deploy
  #       env:
  #         FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}