# Author: Haowei Li
# (It seems like a trend for yml that people put names, so I do it too)

# The purpose of this yml file is to run some tests on the client to see if everything runs as supposed to
# client is based on React.JS
name: Unit Test
on:
  push:
    branches:
       - main
       - dev

jobs:
  tests:
    runs-on: ubuntu-latest
  
    steps: 
      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - uses: stefanoeb/jest-action@1.0.3
      - name: tests
        working-directory: client
        run: npm test
