# Author: Haowei Li
# (It seems like a trend for yml that people put names, so I do it too)

# The purpose of this yml file is to run some tests on the client to see if everything runs as supposed to
# client is based on React.JS
name: Unit Test
on:
  push:
    branches:
       - main
       - dev
defaults:
  run:
    working-directory: client
jobs:
  tests:
    runs-on: windows-latest
  
    steps: 
      - uses: actions/checkout@v2
      
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      
      - name: npm install, build, and test
        run: |
          npm install
          npm install -D jest-environment-jsdom
          npm run build --if-present
          npm run test --if-present
